### ISSUE TITLE
Why numbers of wins, losses or ties are NOT integers?

### ISSUE THREAD

**Issue by matsouaka** [bozenne/BuyseTest#12]
I was comparing the results from the BuyseTest and WINS R packages, using the veteran data (also  used in the tutorial https://cran.r-project.org/web/packages/BuyseTest/vignettes/overview.pdf) and the results are drastically different. While either package may have its own flaws, but what stroke me with the BuyseTest package is the fact that, assuming no censoring, the number of wins, losses, and ties are NOT integers as expected. I suspect that how these are calculated may help uncover the mystery, but will be helpful if I can get clarifications on:
1. The discrepancy between the two packages;
2. Why are there different numbers (or proportions) of wins, losses, and ties?
3. Why, in the context of BuyseTest, the above numbers are decimals, instead of integers?
4.  How that is reflected in the final results if I account for censoring in the analyses?

Hopefully, you can help me uncover the mystery.

**Comment by bozenne** [comment]
Dear Matsouaka,

Thanks for your message. Unfortunately, it is hard for me to answer since you do not provide a reproducible example so I can only guess. If I consider the veteran data and use the time outcome ignoring censoring I get:
```
library(BuyseTest)
library(survival)

BT <- BuyseTest(trt ~ cont(time), data = veteran, trace = FALSE)
fav <- coef(BT, statistic = "count.favorable")
unfav <- coef(BT, statistic = "count.unfavorable")
neutral <- coef(BT, statistic = "count.neutral")
n.pairs <- fav+unfav+neutral
c(fav = fav, unfav = unfav, neutral = neutral, pairs = n.pairs)
```

I get
    fav   unfav neutral   pairs 
   2117    2553      22    4692 

Which are integers as you rightly expected. If you have a case involving binary/categorical/continuous uncensored outcome returning decimal win/loss/ties please send me a reproducible example and I'll have a look.

**Comment by bozenne** [comment]
I get 
[1] 2117 2553   22


Which are integers as you rightly expected.  If you have a case involving binary/categorical/continuous uncensored outcome returning decimal win/loss/ties please send me a reproducible example and I'll have a look.

**Comment by bozenne** [comment]
By default you can get the Net Benefit and the Win Ratio

```
confint(BT, statistic = "netBenefit")
##         estimate         se   lower.ci upper.ci null   p.value
## time -0.09292413 0.09946685 -0.2819898 0.103089    0 0.3529747
## same as (fav - unfav)/n.pairs

confint(BT, statistic = "winRatio")
##       estimate        se lower.ci upper.ci null   p.value
## time 0.8292205 0.1671848 0.558539 1.231081    1 0.3529735
## same fav/unfav
```

To get the Win Odds/Success Odds one has to set add.halfNeutral to TRUE when calling BuyseTest
 ```
BT2 <- BuyseTest(trt ~ cont(time), data = veteran, add.halfNeutral = TRUE)
confint(BT2, statistic = "winRatio")
##       estimate        se  lower.ci upper.ci null   p.value
## time 0.8299532 0.1665437 0.5600748 1.229876    1 0.3529747
## same as (fav+0.5*neutral)/(unfav+0.5*neutral)
```

**Comment by bozenne** [comment]
I could not find any package called WIN but maybe you meant WINS. I retrived the same estimate (up to rounding) using this package:
```
veteran2 <- data.frame(arm = veteran$trt, id = 1:NROW(veteran), stratum = 1,
                       Delta_1 = 1, Y_1 = veteran$time, Start_time = 0)

win.stat(data = veteran2, ep_type = "tte", arm.name = c("2","1"),
         priority = 1, alpha=0.05, digit = 3, weight = "unstratified", pvalue = "two-sided",
         censoring_adjust = "No")
```

The outcome type for all the endpoints:  tte 
This analysis is unstratified. 
The Dong et al.'s method to calculate variance is used. 

 Win Ratio : 0.829 
 
 two-sided p-value is:  0.348 
 Lower limit of 95 % CI of the win ratio:  0.561 
 Upper limit of 95 % CI of the win ratio:  1.226 
 
 
 Net Benefit : -0.093 
 
 two-sided p-value is:  0.350 
 Lower limit of 95 % CI of the net benefit:  -0.288 
 Upper limit of 95 % CI of the net benefit:  0.102 
 
 
 Win Odds : 0.830 
 
 two-sided p-value is:  0.348 
 Lower limit of 95 % CI of the win odds:  0.562 
 Upper limit of 95 % CI of the win odds:  1.225

**Comment by bozenne** [comment]
Note that by default BuyseTest uses a transformation to obtain confidence intervals and p-value with better small sample properties. Not using  a transformation for the Net Benefit leads to results nearly identicals to WINS:
```
confint(BT, statistic = "netBenefit", transform = FALSE)
##        estimate         se   lower.ci  upper.ci null   p.value
## time -0.09292413 0.09946685 -0.2878756 0.1020273    0 0.3501894
```

**Comment by matsouaka** [comment]
Hi Bozenne,
First of all, thank you for your prompt response. I appreciate your willingness to help. 
Yes, you're right. I meant to say WINS package (not WIN) as you rightfully indicated in your response. 
In your response, using the veteran data, you use time as a continuous variable in both packages. When you use it as a time-to-event endpoint and add censoring status, that where you find non-integers numbers of wins and losses as well as different estimates for the net benefit and win ratio.
Nevertheless, I did figure out what was the issue. In BuyseTest, the default scoring rule is "Peron", which yields non-integers since it accounts for censoring via weighting. The WINS uses only "Gehan". Thus, to get the same results with either package, one needs to specify that scoring.rule = "Gehan" in BuyseTest

**Comment by bozenne** [comment]
Great, I think that solve the issues then.

**Comment by matsouaka** [comment]
Yes, thank you for your help.
