### ISSUE TITLE
Handling of ties in time-to-event outcomes

### ISSUE THREAD

**Issue by graemeleehickey** [bozenne/BuyseTest#13]
If a patient in the treatment arm has a failure at time $T$, but a patient in the control arm is lost-to-follow-up also at time $T$ (so is right-censored), Table III in Buyse (2010) declares the pair as uninformative. The `BuyseTest` package also uses this logic, as can be seen in the dummy example below.

```r
dat <- data.frame(
  time = c(10, 10),
  event = c(0, 1),
  treat = c(0, 1)
)
 
test <- BuyseTest(
  treat ~ TTE(time, status = event),
  data = dat,
  method.inference = "u-statistic",
  keep.pairScore = TRUE,
  scoring.rule = "Gehan")
 
summary(test, statistic = "winRatio", percentage = FALSE)
```

I have contacted Prof. Buyse and he confirms this is an error. I have also checked Gehen (1965), and indeed it looks like the inequalities are not aligned. In the absence of a threshold (i.e., $\tau = 0$), the scoring should be:

![image](https://github.com/bozenne/BuyseTest/assets/5270977/e9306cfd-c18b-4a07-93df-056a526db144)

### References

Buyse M. ‘Generalized Pairwise Comparisons of Prioritized Outcomes in the Two-Sample Problem’. Statistics in Medicine 29, no. 30 (2010): 3245–57. https://doi.org/10.1002/sim.3923.

Gehan EA. A generalized Wilcoxon test for comparing arbitrarily singly censored samples. Biometrika 1965; 52:203--223.

**Comment by bozenne** [comment]
Thanks, I've modified the Gehan scoring rule accordingly and added your example in the tests. 
Can you also check that the new Github version (3.0.3) behaves as you expected?

**Comment by bozenne** [comment]
The new version has been pushed on CRAN
