### ISSUE TITLE
More prominent mention of win odds and bug in calculation thereof

### ISSUE THREAD

**Issue by aghaynes** [bozenne/BuyseTest#14]
Hi! Nice package for generalised pairwise comparisons! :)

Considering that win odds has benefits over win ratio (see e.g. [Ajufo et al](https://www.sciencedirect.com/science/article/pii/S2452302X23002024)), maybe it's worth making it more prominent in the helpfiles, in particular [here](https://github.com/bozenne/BuyseTest/blob/46a3e368761b1c615ecde73e5266c5603a48e50b/R/BuyseTest.R#L42)? 

**UPDATE:**

A colleague looked into this a bit and it seems that your calculation of the win odds via this approach is incorrect. You seem to add half the ties at each endpoint. The correct approach is to add half the ties from the last endpoint (as most of the ties from the first level have (hopefully) been resolved by the second level)...

**Comment by bozenne** [comment]
Thanks, I'll have a look and come back to you.

**Comment by bozenne** [comment]
So I have made a new version (3.0.5) that should fix the bug your colleague mentioned. Here is an example:
```
library(BuyseTest)
set.seed(1)
ddd <- simBuyseTest(1e2)

e.BT <- BuyseTest(treatment ~ bin(toxicity) + cont(score, threshold = 0.1) + tte(eventtime, status), data = ddd, add.halfNeutral = TRUE)
summary(e.BT, statistic = "winRatio")
##  endpoint threshold total(%) favorable(%) unfavorable(%) neutral(%) uninf(%)  delta  Delta CI [2.5% ; 97.5%] p.value 
##  toxicity             100.00        20.80          28.80      50.40        0 0.8519 0.8519   [0.6464;1.1227] 0.25494 
##     score       0.1    50.40        27.23          20.26       2.91        0 1.3210 0.9796   [0.7107;1.3502] 0.89986 
## eventtime               2.91         1.29           1.62       0.00        0 0.7914 0.9730   [0.7057;1.3415] 0.86730 

## delta (priority specific win odds)
(e.BT@count.favorable+0.5*e.BT@count.neutral)/(e.BT@count.unfavorable+0.5*e.BT@count.neutral)
##    toxicity score_t0.1 eventtime
## 1 0.8518519   1.320976  0.791384
## Delta (win odds up to current priority)
(cumsum(e.BT@count.favorable)+0.5*e.BT@count.neutral)/(cumsum(e.BT@count.unfavorable)+0.5*e.BT@count.neutral)
##    toxicity score_t0.1 eventtime
## 1 0.8518519    0.97961  0.972992
```

**Comment by bozenne** [comment]
I've also updated uncertainty calculation (hopefully correctly!). On the previous example it seems while the estimate differs substantially, the p-value is quite similar between win odds and win ratio 
```
e.BT0 <- BuyseTest(treatment ~ bin(toxicity) + cont(score, threshold = 0.1) + tte(eventtime, status), data = ddd, add.halfNeutral = FALSE)
summary(e.BT0, statistic = "winRatio")
 ##  endpoint threshold total(%) favorable(%) unfavorable(%) neutral(%) uninf(%)  delta  Delta CI [2.5% ; 97.5%] p.value 
 ##  toxicity             100.00        20.80          28.80      50.40        0 0.7222 0.7222   [0.4124;1.2648] 0.25500 
 ##     score       0.1    50.40        27.23          20.26       2.91        0 1.3440 0.9790   [0.7035;1.3624] 0.89986 
 ## eventtime               2.91         1.29           1.62       0.00        0 0.7914 0.9730   [0.7057;1.3415] 0.86730 
```

**Comment by bozenne** [comment]
Regarding your first comment, my approach is to separate the software considerations (what is a valid input --> @ param) from the statistical consideration (which in my mind belong more to a vignette or detail section). Also I consider it is mostly up to the user to decide what is wise to use, the software is only there to perform computations in an 'easy' way.

All of this being said, the package do list related scientific articles in the overview of the package documentation and the reference you suggest has been [added](https://github.com/bozenne/BuyseTest/blob/master/R/BuyseTest-package.R#L54) among other papers on ' Discussion about the relevance of GPC based measures of treatment effect'.
I have also updated the future version of the vignette similarly: see the top of page 8 at https://github.com/bozenne/BuyseTest/blob/master/inst/doc-software/overview.pdf 

If you have a more specific phrasing in mind let me know and I will consider whether and how it can be included.

**Comment by aghaynes** [comment]
Thats great, thanks!

**Comment by bozenne** [comment]
The new version has been pushed (3.0.5) to CRAN.
