### ISSUE TITLE
Asymptotic inference error

### ISSUE THREAD

**Issue by graemeleehickey** [bozenne/BuyseTest#2]
The `method.inference = "asymptotic"` option is returning erroneous confidence intervals.

An example is:
```r
data(veteran,package="survival")

BT.keep <- BuyseTest(trt ~ tte(time, threshold = 20, censoring = "status") + cont(karno),
                     data = veteran, keep.pairScore = TRUE, method.tte = "Gehan", 
                     trace = 0, method.inference = "asymptotic")

summary(BT.keep, statistic = "winRatio")
```

which returns a 95% CI of [-1.1414, 2.7763]. However, the lower confidence interval should be non-negative.

I am getting similar results on my own datasets with purely TTE outcomes.

**Comment by bozenne** [comment]
Hum, I have fixed a few bugs in the current Github version.
Can you update the package using:

library(devtools)
install_github("bozenne/BuyseTest")

and tell me if this is still the case? Thanks.

Note: strictly speaking CI can be valid even though they take values outside the interval of definition of the parameter of interest. They "only" need to have correct coverage. Ideally they should also be as short as possible; in that sense you rightfully point out that they are strangely wide toward useless values. In the current Github version a log transformation is used (by default) to ensure that the CI is within [0;+\infty]. So the problem should no more occur.

**Comment by graemeleehickey** [comment]
Thank you! Indeed, the latest version seems to give more sensible answers. However, there seems to be a bug for the bootstrap inference option in the latest version. I now get the following error.

Example:
```r
data(veteran,package="survival")
BT.keep <- BuyseTest(trt ~ tte(time, threshold = 20, censoring = "status") + cont(karno),
                      data = veteran, keep.pairScore = TRUE, scoring.rule = "Gehan", 
                      trace = 0, method.inference = "bootstrap")
summary(BT.keep, statistic = "winRatio")
```

returns the following error message: `Error in switch(attr(outConfint, "method.ci.boot"), gaussian = "quantiles of a Gaussian distribution",  :  EXPR must be a length 1 vector`

**Comment by bozenne** [comment]
Oupps I'll have a look at it in the following days and make a patch - thanks for the feedback

**Comment by bozenne** [comment]
I have pushed a new version on the branch "master".
So just do once more 
`library(devtools)
 install_github("bozenne/BuyseTest")`
and that should fix the issue.

I have also put your example in the [tests](https://github.com/bozenne/BuyseTest/blob/development/tests/testthat/test-BuyseTest-previousBug.R).

I will update the CRAN in the following weeks I still have a few things I would like to do before.

**Comment by graemeleehickey** [comment]
Fantastic -- thank you!
