### ISSUE TITLE
Empty vignettes on CRAN?

### ISSUE THREAD

**Issue by alexploner** [bozenne/BuyseTest#8]
It appears that the vignettes with the CRAN version of the package are empty:

<https://cran.r-project.org/web/packages/BuyseTest/vignettes/overview.pdf>
<https://cran.r-project.org/web/packages/BuyseTest/vignettes/wilcoxonTest.pdf>

Installation & check of the source shows that this is not just a build error, as the content looks like this:
```
%\VignetteIndexEntry{BuyseTest: overview}
%\VignetteEngine{R.rsp::asis}
%\VignetteKeyword{PDF}
%\VignetteKeyword{HTML}
%\VignetteKeyword{vignette}
%\VignetteKeyword{package}
```
I'm not sure whether this is just outdated (as the current version has two fine vignettes), but it's more than a bit unusual for a CRAN package, so... for your attention.

**Comment by bozenne** [comment]
Thanks for letting me know. 
I think something went wrong when I compressed the pdf for the CRAN submission. I'll resubmit a new version with proper vignettes in a few weeks. In the meantime, you can find the pdf of the vignettes here:
https://github.com/bozenne/BuyseTest/blob/master/vignettes/overview.pdf
https://github.com/bozenne/BuyseTest/blob/master/vignettes/wilcoxonTest.pdf
Sorry for the inconvenience.

**Comment by bozenne** [comment]
A new version of the package is now on CRAN. The vignettes now appear correctly.
