### ISSUE TITLE
p-value in permutations :  display 0 instead of 2.2e-16

### ISSUE THREAD

**Issue by SamSalvaggio** [bozenne/BuyseTest#9]
Hi,

I was wondering whether it would be possible to display 0 instead of 2.2e-16 for very small p.values in the output of summary(GPC), as in my understanding, it happens when no permutations was above the real data.

Thanks in advance !
Best regards,
Samuel

**Comment by bozenne** [comment]
Dear Samuel,

You should use the confint function to extract values without formating.

In the new version of BuyseTest (2.3.9) I have modified how the p-values are computed with permutation to avoid to output p-values of 0, e.g. see [1]. I use the "Upper bound" estimator which should be good enough as soon as one uses a large number of permutation. I have added an option to move back to the previous behavior, see example below:

`
library(BuyseTest) ## version 2.3.9

set.seed(1)
dt <- simBuyseTest(50, argsCont = list(mu.T = 100, mu.C = 1)) ## extremely large difference so always in favor of treatment
GPC.perm <- BuyseTest(treatment~cont(score),
                      data=dt, trace = FALSE,
                      method.inference = "permutation")

BuyseTest.options(add.1.pperm = FALSE)
confint(GPC.perm)
##  estimate       se lower.ci upper.ci null p.value
## score        1 0.117439        1        1    0       0

BuyseTest.options(add.1.pperm = TRUE)
confint(GPC.perm)
##   estimate       se lower.ci upper.ci null     p.value
## score        1 0.117439        1        1    0 0.000999001
`

[1] doi: 10.2202/1544-6115.1585.

**Comment by SamSalvaggio** [comment]
Thanks a lot !!
